### ISSUE TITLE
how to use minirocket_multi and HydraMultivariate together?

### ISSUE THREAD

**Issue by mohitsawwalakhe** [angus924/hydra#3]
so (sample, feature, length) gets transformed into (sample, features) by both mini rocket multi and hydra multi, so should I just transform the data separately and combine them (sample, rocket feature + hydra feature)? or is any alternative way present?

**Comment by angus924** [comment]
Hi @mohitsawwalakhe, good question.

Yes, the best way to do it at the moment is just to run each transform separately and concatenate the features, then pass the whole lot to the classifier, just like you've suggested.
