### ISSUE TITLE
Why use simple linear classifiers?

### ISSUE THREAD

**Issue by Active2626** [angus924/hydra#5]
Thank you for your great works (i.e., rocket, minirocket, multirocket and hydra), which are really insightful and valuable!

I am curious why you use simple linear classifiers in all your works. I guess there may be two reasons. First, the feature dimension is large, so it is better to select simple classifiers with fewer parameters. Second, simple linear classifiers really work fine and achieve the SOTA on the UCR archive. Are there any other reasons?

Since the random convolution kernel transform is highly integrated and independent of subsequent classifications, I wonder if it is feasible to make some efforts on the classifiers.

Thank you for your time!

**Comment by angus924** [comment]
Hi @Active2626, good question.  The main reasons for using linear classifiers are that they are simple and "fast", while achieving high accuracy for many tasks (esp. the small datasets in the UCR archive).  This demonstrates that even relatively simple models can achieve high accuracy on certain tasks, i.e., that more complex models may not be necessary.

Having said that, of course, given a sufficient quantity of data, nonlinear models and learned features are almost certainly going to be more effective, unless there are some particular characteristics of the problem which still favor linear classifiers (e.g., computational restrictions).

**Comment by Active2626** [comment]
Many thanks for your reply! 

I have one more question. 

In ROCKET, it is stated that there is a tradeoff between classification accuracy and computation time, and with the increase of kernel number, the performance further improves (i.e., mean in accuracy increases and stand deviation in accuracy diminishes). Also, the references using random convolution kernels [1,2]  also use a large number of random kernels. It seems that without considering computation expense, the more random kernels, the better performance, at least no harm to accuracy. Is that correct? 

Recently I read a paper based on MINIROCKET that stated a portion of random kernels may not positively contribute to performance and proposed to use a genetic algorithm to prune redundant kernels, which seems to contradict the insight of random convolution kernels.

Multiple kernels in combination can capture complex patterns. My question is, are there noisy kernels in many random kernels? If yes, is pruning able to improve the performance? If not, what role does one random kernel play in the combinations?

I am not sure if I make myself clear. Anyway, look forward to your reply!

[1] Morrow A, Shankar V, Petersohn D, et al. Convolutional kitchen sinks for transcription factor binding site prediction[J]. arXiv preprint arXiv:1706.00125, 2017.
[2] Jiménez A, Raj B. Time signal classification using random convolutional features[C]//ICASSP 2019-2019 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP). IEEE, 2019: 3592-3596.

**Comment by angus924** [comment]
Hi @Active2626, perfectly clear, great questions.

> It seems that without considering computation expense, the more random kernels, the better performance, at least no harm to accuracy. Is that correct?

Broadly speaking, yes, this is what I would expect: more kernels leads to better performance, but with a few important caveats including, e.g.:

- Architecture is important—for example, for many time series datasets having kernels with different dilations appears to improve accuracy a lot.  You could add a bajillion random kernels to a model that doesn't use dilation and it would never reach the accuracy of a much smaller model that did incorporate dilation—this is likely to be true to some extent for many other aspects of a model (e.g., number of layers, use of layer norm, residual connections, etc.).
- The classifier will have an impact—the size of the dataset and the type and strength of regularization used by the classifier will affect the result—you can observe something like this in the context of double descent (which you can produce with rocket): keep adding random kernels (with no or nominal regularization), at first error will decrease then increase ("traditional" regime), then as the number of kernels grows larger than the number of samples, error will decrease again.  Not necessarily a straightforward relationship between number of kernels and accuracy.
- If you are adding more and more kernels, you are likely to run into diminishing returns (1,000,000 kernels is unlikely to be much better than 100,000 kernels which, in turn, is unlikely to be much better than 10,000 kernels, etc.), unless there is something about the kernels you are adding that is "different" (e.g., kernel size, dilation, something about the frequency response of the kernel, whether the kernel operates on the input or the 1st, 2nd, whatever derivative, etc.).  I suppose this is related to the first point... other things that come to mind are using different pooling mechanisms.  A typical multilayer CNN is a bit different from something like rocket in this sense (multiple layers, hierarchical features, etc.).

> Recently I read a paper based on MINIROCKET that stated a portion of random kernels may not positively contribute to performance and proposed to use a genetic algorithm to prune redundant kernels, which seems to contradict the insight of random convolution kernels.
> 
> Multiple kernels in combination can capture complex patterns. My question is, are there noisy kernels in many random kernels? If yes, is pruning able to improve the performance? If not, what role does one random kernel play in the combinations?

In my experience, in practice it's very hard to do sensible feature selection or kernel selection with random kernels, especially with smaller datasets.  There are a few issues.  In expectation, each kernel (in isolation) will only capture a tiny amount of information.  It is very hard to pick out those tiny differences and decide which kernels to keep or discard.  Another way to look at this is that the classifier is combining a tiny amount of information from a very large number of kernels.  No particular kernel is likely to be particularly important but, likewise, no particular kernel is likely to be completely useless.  (Also consider, however, how much information can you derive from a single learned kernel anyway?)  The decision boundary learned by the classifier will be a product of combinations of large numbers of features... you might have to add or remove large groups of kernels to see any material difference in classification, and there may not be a clear dividing line between "good" and "bad" kernels.  In addition, for smaller datasets, there's often really simply not enough data to draw sensible conclusions.

On the other hand, in some sense there is a lot of redundancy in a large set of random kernels: e.g., minirocket achieves similar accuracy to rocket with just 84 kernels (not including dilation).  A lot of kernels pick up broadly similar features (e.g., lots of different kernels will pick up positive gradients or negative gradients, etc.).  Some kind of process to iteratively generate random kernels or groups of random kernels and then measure loss or accuracy could work.  I would guess (I might be wrong), that if you have sufficient data it's probably more efficient to just learn the kernels in the firs place.  (However, I suppose it might be possible to learn models with which are different from models learned by gradient descent, but that's complete speculation on my part.)

**Comment by Active2626** [comment]
Hi @angus924,  thank you so much for your kind help! Your valuable work and kind reply really mean a lot to me. It will take time for me to digest your informative and insightful answers. I really appreciate your help and time :)

**Comment by angus924** [comment]
No worries @Active2626.

These are just my thoughts and impressions.  I may be wrong about some things, maybe most things!  It's always important to try things out and experiment.

If there's a better way to do something, or it's possible to show that the way we're thinking about something is wrong, that would be great!

Most of the interesting stuff I have discovered has been more or less by accident.

**Comment by Active2626** [comment]
Many thanks for your advice!
