### ISSUE TITLE
Randomness causes the model to be unstable and impractical!

### ISSUE THREAD

**Issue by shushan2017** [angus924/hydra#7]
Due to the presence of random numbers, the performance of the model is very unstable, and the quality of the results depends entirely on luck. Can `self. W` be pre trained to make the model stable and robust? thanks

**Comment by angus924** [comment]
The kernels are random, so there will be variance between results.  However, as we use a relatively large number of kernels, and in a sense the features produced by the kernels are averaged over multiple groups of kernels, the variance should not be particularly high.  In other words, the results from one set of kernels should be reasonably similar to the results from another set of kernels.  (Although is is not at all the same thing, I would draw a loose analogy to something like a random forest or extremely randomised trees, where the constituent trees are random, but you get relatively consistent results from using large numbers of random trees.)

If you could give me a specific example of where you are finding the variance too high (e.g., a particular dataset), I can try to figure out what is going on.

Some alternatives if you are looking for less randomness / variance would be: (a) to use a fixed set of kernels (e.g., some variation of the kernels used in MiniRocket); or (b) as you suggest, training the kernels end-to-end.  For (b), you could only use max pooling, as the argmax operation has no gradient, but it does work and I have used used it for some datasets, so it is entirely possible to take this approach.

Does this help at all?

**Comment by shushan2017** [comment]
My project involves unbalanced classification, overlapping multi model ensemble, and I replace the default Linear classifier with lightgbm. It is complex as a whole, which may be the reason for large differences in results. Thank you very much! And I tried MiniRocket and found that it still seems to be influenced by random numbers.

In fact, the problem I am facing is that I cannot obtain identical convolutional kernels. That is, the convolutional kernel obtained randomly in the first run cannot be exactly the same as the convolutional kernel obtained in the second run. All I think of is recording the random number each time and saving it as a weight, which is read in the second run. This is a foolish approach. I think there should be better pre training methods.
