### ISSUE TITLE
what does it mean  hydra_multivariate.py  is experimental

### ISSUE THREAD

**Issue by Sandy4321** [angus924/hydra#8]
what does it mean  hydra_multivariate.py
 is experimental

**Comment by angus924** [comment]
It just means that it is unpublished and not thoroughly tested, there may be various issues with it, but basically it should work.  There may be better ways of extending the method to multivariate data, but this is at least one way to do it.

**Comment by Sandy4321** [comment]
ley me try 
do yo have example code from 0 to end for multivariate data
meaning download and read data 
then make predictions and calculate performance
